### PR TITLE
Updated README.md: Added table for indexing adopters and integrations

### PR DESCRIPTION
**Pull request by DarikshaAnsari**
Made changes for [#6 
](https://github.com/in-toto/friends/issues/6)

### CODE REVIEW

**Comment by DarikshaAnsari** [comment]
@adityasaky PTAL !

**Comment by adityasaky** [comment]
@in-toto/in-toto-steering-committee-itsc

**Review by trishankatdatadog — COMMENTED** [review]
Thanks for your PR, @DarikshaAnsari, very helpful! 🎉 

Before we merge, could we please fix the links to the logos? Note that they are currently either hosted externally, or under your account 🙂

**Comment by DarikshaAnsari** [comment]
I will fix the issue with links, can I make one folder assets and use logo images locally?

**Comment by trishankatdatadog** [comment]
> I will fix the issue with links, can I make one folder assets and use logo images locally?

One would think so, but requires some research...

**Comment by DarikshaAnsari** [comment]
I have changed the links ,PTAL.

**Review by SantiagoTorres — APPROVED** [review]
Thank you!

**Pull request merged**
